name: Run Noterepo Tests

on:
  push:
    branches:  
    - '**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nodejs 20 Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack
        run: corepack enable && corepack install # use the in-repo yarn version

      - name: Setup Yarn in Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn' # uses the system node, which was updated prior.

      - name: Install Dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn run test:e2e && yarn run test
